apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-proxy-api
spec:
  selector:
    matchLabels:
      app: http-proxy-api
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: http-proxy-api
    spec:
      containers:
        - name: http-proxy-api
          image: jiamingnj/http-proxy-api:latest
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          env:
            - name: PORT
              value: "8081"
