apiVersion: v1
kind: Service
metadata:
  labels:
    app: http-proxy-api
  name: http-proxy-api
spec:
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
  selector:
    app: http-proxy-api